CREATE TABLESPACE APFIS_DATOS   DATAFILE 'D:\oraclexe\oradata\XE\APFIS_DATOS.ORA'   SIZE 50M ;
CREATE TABLESPACE APFIS_INDICES DATAFILE 'D:\oraclexe\oradata\XE\APFIS_INDICES.ORA' SIZE 50M ;

CREATE USER APFIS IDENTIFIED BY APFIS DEFAULT TABLESPACE APFIS_DATOS;
GRANT "DBA" TO "APFIS" WITH ADMIN OPTION;
GRANT UNLIMITED TABLESPACE TO "APFIS" WITH ADMIN OPTION;
ALTER USER "APFIS" DEFAULT ROLE ALL;

CREATE ROLE ROL_APFIS NOT IDENTIFIED;

GRANT ALTER ANY TABLE TO ROL_APFIS;  
GRANT CREATE TABLE TO ROL_APFIS;


GRANT ROL_APFIS TO APFIS;


--GRANT EXECUTE ON dbms_sys_sql TO system WITH GRANT OPTION;
---GRANT EXECUTE ON dbms_sql TO system WITH GRANT OPTION;
--GRANT EXECUTE ON sys.dbms_sys_sql TO derweb;
--GRANT EXECUTE ON sys.dbms_sql TO derweb;


